accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('profile/<int:pk>/update', views.ProfileUpdate.as_view(), name='profile_update'),
    path('profile/<int:pk>/password', views.PasswordChange.as_view(), name='password'),  # 追記
    path('profile/<int:pk>/password/complete', views.PasswordChangeComplete.as_view(), name='password_complete'), 
    path('profile/<int:pk>/delete/',views.UserDeleteView.as_view(), name='delete')
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('management/', views.InformationView.as_view(), name="management"),
    path('management/books/create/', views.BookCreateView.as_view(), name="books_create"),
    path('management/books/delete/<int:pk>/', views.BookDeleteView.as_view(), name="books_delete"),
    path('management/books/retrieve_book/', views.retrieve_book, name='retrieve_book'),
    path('management/books/update/<int:pk>/', views.BookUpdateView.as_view(), name="books_update"),
    path('management/books/list/', views.BookManagementListView.as_view(), name="books_list"),
    path('management/reviews/', views.ReviewListView.as_view(), name="reviews_list"),
    path('management/reviews/delete/<int:pk>/', views.ReviewDeleteView.as_view(), name="reviews_delete"),
    path('management/storage/', views.StorageListView.as_view(), name="storage_list"),
    path('management/storage/create/', views.StorageCreateView.as_view(), name="storage_create"),
    path('management/storage/update/<int:pk>/', views.StorageUpdateView.as_view(), name="storage_update"),
    path('management/storage/delete/<int:pk>/', views.StorageDeleteView.as_view(), name="storage_delete"),
    path('management/lending/', views.LendingManagementView.as_view(), name="lending_management"),
    path('management/lending/reservation/', views.LendingReservationView.as_view(), name="lending_reservation"),
    path('management/lending/cancel/', views.LendingCancelView.as_view(), name="lending_cancel"),
    path('management/lending/now/', views.LendingNowView.as_view(), name="lending_now"),
    path('management/lending/return/', views.LendingReturnView.as_view(), name="lending_return"),
    path('management/lending/overdue/', views.LendingOverdueView.as_view(), name="lending_overdue"),
    path('bookshelf/', views.BookshelfView.as_view(), name="bookshelf"),
    path('search/', views.BookSearchView.as_view(), name="book_search"),
    path('<int:pk>/', views.BookDetailView.as_view(), name="book_detail"),
    path('reservation/<int:book_pk>/', views.BookReservationView.as_view(), name="book_reservation"),
    path('reservation/<int:book_pk>/done/<int:pk>/<str:user_token>/<str:url_token>/', views.BookReservationDoneView.as_view(), name="book_reservation_done"),
    path('rent/<int:book_pk>/', views.BookRentView.as_view(), name="book_rent"),
    path('rent/<int:book_pk>/done/<int:pk>/<str:user_token>/<str:url_token>/', views.BookRentDoneView.as_view(), name="book_rent_done"),
    path('rent/list/', views.RentListView.as_view(), name='rent_list'),
    path('return/<int:pk>/<str:user_token>/<str:url_token>/', views.ReturnBookView.as_view(), name="return_book"),
    path('cancel/<int:pk>/<str:user_token>/<str:url_token>/', views.CancelReservationView.as_view(), name="cancel_reservation"),
    path('review/<int:pk>/<str:user_token>/<str:url_token>/', views.ReviewView.as_view(), name='review'),
    path('review/<int:pk>/done/<str:user_token>/<str:url_token>/', views.ReviewDoneView.as_view(), name="review_done"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static, serve
from django.conf.urls import handler403

handler403 = 'accounts.views.custom_permission_denied_view'

urlpatterns = [
    path('', include("accounts.urls")),
    path('admin/', admin.site.urls),
    path('book/',include("book.urls") ),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

book/models.py
from django.db import models
from project import settings
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
import re

class Storage(models.Model):
    floor = models.IntegerField(verbose_name="階数", null=True)
    area = models.CharField(max_length=30, verbose_name='エリア', null=True)
    def __str__(self):
        return f"{self.floor}階 {self.area}"
    class Meta:
        ordering = ['floor', 'area']
        constraints = [
            models.UniqueConstraint(fields=['floor', 'area'], name='unique_floor_area')
        ]
    
    def clean(self):
        # 禁止文字が含まれているかチェック
        if re.search(r"[;'\"]", self.area):
            raise ValidationError("不正な文字が含まれています。")
        return super().clean()

class Books(models.Model):
    isbn = models.CharField(
        max_length=13,
        verbose_name='ISBN',
        validators=[
            RegexValidator(
                regex=r'^97\d{11}$',
                message='ISBNは「97」で始まる13桁の数字である必要があります。',
            )
        ],
        blank=False
    )
    title = models.CharField(max_length=100, verbose_name='タイトル', blank=False)
    author = models.CharField(max_length=100, verbose_name='著者' , blank=False)
    publisher = models.CharField(max_length=100, verbose_name='出版社', null=True, blank=True)
    publication_date = models.DateField(verbose_name='出版日', null=True, blank=True)
    category = models.CharField(max_length=100, verbose_name='カテゴリー', null=True, blank=True)
    image_link = models.URLField(verbose_name='画像リンク', null=True, blank=True)
    price = models.IntegerField(verbose_name='価格', null=True, blank=True)
    edition = models.IntegerField(verbose_name='版数', null=True, blank=True)
    purchase_date = models.DateField(verbose_name='購入日',null=True, blank=True)
    storage = models.ForeignKey(Storage, on_delete=models.SET_NULL,verbose_name='保管場所' ,null=True, blank=False)
    is_lend_out = models.BooleanField(
        verbose_name=('貸出状況'),
        default=False
    )
    
    def __str__(self):
        return self.title
    
class Review(models.Model):
    books = models.ForeignKey(Books, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.TextField(verbose_name="レビュー内容")
    def clean(self):
        # 禁止文字が含まれているかチェック
        if re.search(r"[;'\"]", self.comment):
            raise ValidationError("不正な文字が含まれています。")
        return super().clean()

    def __str__(self):
        return f"{self.user} - {self.books.title}"

class Lending(models.Model):
    books = models.ForeignKey(Books, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    reservation_checkout_date = models.DateField(verbose_name='予約貸出日',null=True, blank=True)
    reservation_scheduled_return_date = models.DateField(verbose_name='予約返却予定日',null=True, blank=True)
    checkout_date = models.DateField(verbose_name='貸出日',null=True, blank=True)
    scheduled_return_date = models.DateField(verbose_name='返却予定日',null=True, blank=True)
    return_date = models.DateField(verbose_name='返却日',null=True, blank=True)
    cancel_date = models.DateField(verbose_name='予約キャンセル日', null=True, blank=True)
    def __str__(self):
        return f"{self.user} - {self.books.title}-{self.reservation_checkout_date}-{self.reservation_scheduled_return_date}-{self.checkout_date}-{self.scheduled_return_date}-{self.return_date}-{self.cancel_date}"

book/forms.py
from django import forms
from django.db import IntegrityError
from uuid import uuid4
from .models import Books, Storage, Lending, Review

class StorageForm(forms.ModelForm):
    class Meta:
        model = Storage
        fields = ['floor', 'area']

    def save(self, commit=True):
        try:
            return super().save(commit=commit)
        except IntegrityError:
            raise forms.ValidationError("この階数とエリアの組み合わせは既に存在します。")

class BookForm(forms.ModelForm):
    class Meta:
        model = Books
        fields =  '__all__'

    def clean_isbn(self):
        isbn = self.cleaned_data.get('isbn')
        return isbn

class BookReservationForm(forms.ModelForm):
    class Meta:
        model = Lending
        fields = ['reservation_checkout_date', 'reservation_scheduled_return_date']

class BookRentForm(forms.ModelForm):
    class Meta:
        model = Lending
        fields = ['checkout_date', 'scheduled_return_date','reservation_checkout_date', 'reservation_scheduled_return_date']
        widgets = {
            'reservation_checkout_date': forms.HiddenInput(),
            'reservation_scheduled_return_date': forms.HiddenInput(),
        }
    
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment']

templates/book/book_rent.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>分散型図書管理アプリ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css' rel='stylesheet' />
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/locale/ja.js'></script>
    <style>
        .fc-unavailable {
            background-color: red;
            pointer-events: none;
        }
        html{
        min-height: 100%;
        position: relative;
        }
        body {
        margin: 0;
        padding: 0;
        margin-bottom: 60px;
        }
        header {
        width: 100%;
        }
        footer {
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 60px;
        }
        .main-title {
            font-size: 1.5rem;
            font-weight: bold;
            margin-bottom: 1rem;
        }
    </style>
    <script> 
        window.onbeforeunload = function() {
            // IE用。ここは空でOKです
        };
        window.onunload = function() {
            // IE以外用。ここは空でOKです
        };
    </script>
</head>
<body class="d-flex flex-column h-100">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'accounts:index' %}">分散型図書管理アプリ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    {% if user.is_authenticated %}
                    <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <form method="POST" action="{% url 'accounts:logout' %}">
                                {% csrf_token %}
                                <button type="submit" class="nav-link">ログアウト</button>
                            </form>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav>
    </header>
  <main class="flex-shrink-0">
    <div class="container mt-5 pt-5">
        {% if user.is_authenticated and not book.is_lend_out  %}
        <div class="d-flex justify-content-end">
            <a href="{% url 'book:book_detail' book.pk %}" class="btn btn-secondary mb-3">本の詳細へ戻る</a>
        </div>
        <div class='main-title border-bottom'>「{{ book.title }}」を借りる</div>
        <form id='rent-form' method="post" action="{% url 'book:book_rent' book.pk %}">
            {% csrf_token %}
            <input type="hidden" id="checkout_date" name="checkout_date">
            <input type="hidden" id="scheduled_return_date" name="scheduled_return_date">
            <input type="hidden" name="book_pk" value="{{ book.pk }}">
        </form>
        <div id='calendar'></div>

        <script>
            $(document).ready(function() {
                var unavailableDates = {{ unavailable_dates|safe }};
                var today = moment().format('YYYY-MM-DD');
                var selectedDate = null;
                var action = 'checkout'; // 初期アクションは貸出日の設定
                $('#calendar').fullCalendar({
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'month',
                    },
                    selectable: true,
                    validRange: {
                        start: today
                    },
                    locale: 'ja',
                    dayRender: function(date, cell) {
                        var formattedDate = date.format('YYYY-MM-DD');
                        // todayがunavailableDatesに含まれる場合、デザインをfc-unavailableにする
                        if (formattedDate === today) {
                            cell.removeClass('fc-today');
                            if (unavailableDates.includes(today)) {
                                cell.addClass('fc-unavailable');
                            }
                        } else if (unavailableDates.includes(formattedDate)) {
                            cell.addClass('fc-unavailable');
                        }
                    },
                    dayClick: function(date, jsEvent, view) {
                        var formattedDate = date.format('YYYY-MM-DD');
        
                        if (action === 'checkout') {
                            if (unavailableDates.includes(formattedDate)) {
                                alert('この日は借りられません');
                            } else {
                                checkoutDate = formattedDate; // 貸出日を保存
                                document.getElementById('checkout_date').value = formattedDate;
                                action = 'return'; // 次回のクリックは返却予定日の設定
                                alert('貸出日を設定しました: ' + formattedDate + ' 次は返却予定日を設定してください。');
                            }
                        } else if (action === 'return') {
                            if (unavailableDates.includes(formattedDate)) {
                                alert('この日は借りられません');
                            } else if (moment(formattedDate).isBefore(checkoutDate) && formattedDate !== checkoutDate) { // 貸出日より過去の日付は設定できないが、同日なら許可
                                alert('返却予定日は貸出日より未来の日付にしてください。');
                            } else if (moment(formattedDate).isAfter(checkoutDate)) { // unavailableDatesをcheckout_dateとscheduled_return_dateの間に設定できない
                                var datesBetween = [];
                                var start = moment(checkoutDate);
                                var end = moment(formattedDate);
                                while (start.isBefore(end)) {
                                    start.add(1, 'days');
                                    datesBetween.push(start.format('YYYY-MM-DD'));
                                }
                                if (datesBetween.some(date => unavailableDates.includes(date))) {
                                    alert('貸出日と返却予定日の間には借りられない日があります。');
                                } else {
                                    document.getElementById('scheduled_return_date').value = formattedDate;
                                    action = 'checkout'; // リセット
                                    alert('返却予定日を設定しました: ' + formattedDate);
                                    document.getElementById('rent-form').submit();
                                }
                            } else if (formattedDate === checkoutDate) { // 貸出日と同じ場合は許可
                                document.getElementById('scheduled_return_date').value = formattedDate;
                                action = 'checkout'; // リセット
                                alert('返却予定日を設定しました: ' + formattedDate);
                                document.getElementById('rent-form').submit();
                            }
                        }
                    }
                });
            });
        </script>
        {% else %}
        <a href="{% url 'book:index' %}" class="btn btn-secondary">ホーム画面へ</a>
        {% endif %}
    </div>
</main>
  <footer class="footer mt-auto py-3 bg-body-tertiary">
    <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
    </div>
  </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

templates/book/books_create.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>本情報管理</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/quagga/0.12.1/quagga.min.js"></script>
    <script>
        function openCamera() {
            // モーダルを表示
            var myModal = new bootstrap.Modal(document.getElementById('cameraModal'));
            myModal.show();
            var modalWidth = document.querySelector('.modal-dialog').offsetWidth;
            var cameraWidth = Math.min(modalWidth, 640); // 最大640pxに制限
            var cameraHeight = Math.min(cameraWidth * 0.625,); // アスペクト比4:3に基づく高さ
        
            Quagga.init({
                inputStream: {
                    name: "Live",
                    type: "LiveStream",
                    target: document.querySelector('#camera'),
                    width: { ideal: 1280 }, // 最大1280px（HD）に設定
                    height: { ideal: 720 }  // アスペクト比を保ちながら720pxに設定
                },
                decoder: {
                    readers: ["ean_reader"]
                },
            }, function (err) {
                if (err) {
                    console.error(err);
                    return;
                }
                console.log("QuaggaJS initialized");
                Quagga.start();
            });
        
            // onDetectedイベントハンドラ
            var onDetectedHandler = function (result) {
                const code = result.codeResult.code;
                if (code.startsWith("97")) {
                    document.getElementById('id_isbn').value = code;
                    alert("ISBNコードが読み取られました: " + code);
                    Quagga.stop();
                    Quagga.offDetected(onDetectedHandler); // リスナーを削除
                    // モーダルを閉じる
                    myModal.hide();
                }
            };

            Quagga.onDetected(onDetectedHandler);
        }

        function fillBookInfo() {
            let isbn = document.getElementById('id_isbn').value;
            if (isbn) {
                $.ajax({
                    url: "{% url 'book:retrieve_book' %}",
                    method: "POST",
                    data: {
                        isbn: isbn,
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function(data) {
                        if (data.error) {
                            alert(data.error);
                        } else {
                            $('#id_title').val(data.title);
                            $('#id_author').val(data.authors);
                            $('#id_publisher').val(data.publisher);
                            $('#id_publication_date').val(data.publication_date);
                            $('#id_category').val(data.category);
                            $('#id_image_link').val(data.image_link);
                            $('#id_price').val(data.price);
                            $('#id_edition').val(data.edition);
                        }
                    },
                    error: function(xhr, status, error) {
                        console.log('Error: ' + error);
                        alert('エラーが発生しました。改めてページを開いてください')
                    }
                });
            } else {
                alert('ISBNを入力してください。');
            }
        };
    </script>
    <style>
        html {
            min-height: 100%;
            position: relative;
        }
        body {
            margin: 0;
            padding: 0;
            margin-bottom: 60px;
        }
        header {
            width: 100%;
        }
        footer {
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
            height: 60px;
        }
        .main-title {
            font-size: 1.5rem;
            margin-bottom: 1rem;
        }
        .form-container {
            display: flex;
            gap: 20px;
        }
        .form-container .form {
            flex: 1;
            max-width: 500px;
        }
        .form-container #camera {
            flex: 1;
            max-width: 200px;
        }
        .form-check-input {
            /* チェックボックスのサイズや外観を調整する例 */
            width: 1.5rem;
            height: 1.5rem;
        }
        .form-check-label {
            /* form-labelと同じスタイルを適用 */
            font-size: 1rem;
            font-weight: 400;
            color: #212529;
        }
    
        .form-check {
            margin-bottom: 1rem; /* 必要に応じて調整 */
        }
        /* モーダルの基本スタイル */
        .modal-dialog {
            max-width: 90%; /* スマートフォンなど小さな画面での最大幅 */
            width: auto;
        }

        /* モーダルの幅を最大640pxに設定し、画面サイズに応じて調整 */
        .modal-dialog {
            max-width: 640px;
            width: 100%;
        }
        /* モーダルコンテンツも100%に設定 */
        .modal-content {
            width: 100%;
        }
        .modal-body{
            width: 100%;
        }
        #camera {
            width: 100%;
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        #camera video{
            width: 100%;
        }
        #camera canvas.drawingBuffer {
            display: none;
        }

        /* スマートフォン（幅が768px以下）の場合 */
        @media (max-width: 768px) {
            .modal-dialog {
                max-width: 100%;
            }
        }
    </style>
    <script> 
        window.onbeforeunload = function() {
            // IE用。ここは空でOKです
        };
        window.onunload = function() {
            // IE以外用。ここは空でOKです
        };
    </script>
</head>
<body class="d-flex flex-column h-100">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'accounts:index' %}">分散型図書管理アプリ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    {% if user.is_authenticated %}
                    <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <form method="POST" action="{% url 'accounts:logout' %}">
                                {% csrf_token %}
                                <button type="submit" class="nav-link">ログアウト</button>
                            </form>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav>
    </header>
    <main class="flex-shrink-0">
        <div class="container mt-5 pt-5">
            {% if user.is_superuser %}
            <div class="d-flex justify-content-end">
                <a href="{% url 'book:books_list' %}" class="btn btn-secondary mb-3">本情報管理画面へ</a>
            </div>
            <div class='main-title  border-bottom'>本の登録</div>
            <div class="form-container">
                <div class="form">
                    <button type="button" onclick="openCamera()" class="btn btn-secondary mb-3">ISBNをスキャン</button>
                    <button type="button" onclick="fillBookInfo()" class="btn btn-secondary mb-3">ISBNから自動入力</button>
                    <div class="text-danger" role="alert">
                        *必須項目を入力してください
                    </div>
                    <form method="post" class="form-signin w-100 m-auto" autocomplete="off">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-floating mb-3 align-items-center">
                            {% if field.field.widget.input_type == 'checkbox' %}
                                <div class="form-check">
                                    <label class="form-check-label" for="{{ field.id_for_label }}">
                                        {{ field.label }}
                                    </label>
                                    {{ field|add_class:"form-check-input" }}
                                </div>
                            {% elif field.field.required %}
                                {{ field|add_class:"form-control" }}
                                <label for="{{ field.id_for_label }}" class="text-danger">
                                    *{{ field.label }}
                                </label>
                                {% if field.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ field.errors|striptags }}
                                </div>
                                {% endif %}
                            {% else %}
                                {{ field|add_class:"form-control" }}
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                </label>
                                {% if field.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ field.errors|striptags }}
                                </div>
                                {% endif %}
                            {% endif %}
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">登録</button>
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-warning">
                                    {{ message }}
                                </div>
                                <button type="submit" name="confirm" class="btn btn-warning">確認して登録</button>
                                <a href="{% url 'book:books_list' %}" class="btn btn-secondary">キャンセル
                                </a>
                            {% endfor %}
                        {% endif %}
                    </form>
                    <script>
                        document.getElementById('myForm').addEventListener('submit', function() {
                            // ボタンを取得
                            const submitButton = document.getElementById('submitButton');
                            
                            // ボタンを無効化
                            submitButton.disabled = true;
                        
                            // 必要に応じて、ボタンのテキストやスタイルを変更することも可能
                            submitButton.innerText = '送信中...';
                        
                            // フォームの送信が続行される
                        });
                        </script>
                </div>
            </div>
            {% else %}
            <a href="{% url 'book:index' %}" class="btn btn-secondary">ホーム画面へ</a>
            {% endif %}
        </div>
        <div class="modal fade" id="cameraModal" tabindex="-1" aria-labelledby="cameraModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <div id="camera" class="d-flex justify-content-center align-items-center"></div>
                </div>
              </div>
            </div>
        </div>  
    </main>
    <footer class="footer mt-auto py-3 bg-body-tertiary">
        <div class="container">
            <span class="text-muted">Place sticky footer content here.</span>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>